### PR TITLE
Add basic groups endpoint

### PR DESCRIPTION
**Pull request by eduardomourar**
Just a basic implementation of some GET methods from the GROUPS endpoint:

[https://docs.gitlab.com/ee/api/groups.html](https://docs.gitlab.com/ee/api/groups.html)

### CODE REVIEW

**Comment by eduardomourar** [comment]
@ngetchell , i need some help to fix the build failing. i would appreciate if you could point me in the right direction.

**Comment by it-praktyk** [comment]
@eduardomourar, you have to create/update markdown-based help. The files are in the folder https://github.com/ngetchell/PSGitLab/tree/master/docs.

They are PlatyPS-like. I write "like" because they can have outdated and due to the bug https://github.com/PowerShell/platyPS/issues/371 can't be updated automatically.

**Comment by it-praktyk** [comment]
BTW, I did some work in groups/members areas too. You can find them at [my fork](https://github.com/it-praktyk/PSGitLab/commits/members). I'll check later if I pushed everything to the public.

**Comment by eduardomourar** [comment]
@it-praktyk , thanks! Also, I guess you did implement most of what I needed, except the projects per group API: `/groups/$GroupId/projects`

**Comment by eduardomourar** [comment]
@it-praktyk , I have made the necessary changes. Could you merge this, please? Thanks.

**Pull request merged**
