### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by TerrapinStation**
Refactored private query function to accommodate for multiple page responses.
Refactored stats cmdlet to use parametersets
Added GetWeek private function for use in Get-GitLabCommitStats since -UFormat was being buggy for me

### CODE REVIEW

**Comment by TerrapinStation** [comment]
@ngetchell could u test this when you get a chance? i refactored the query function to use Invoke-webrequest instead of Invoke-restmethod to get raw html response back since I needed the return headers to determine if the response was multipage or not. Max results were 100 per page for API, so things were returning with missing data.

**Comment by ngetchell** [comment]
Will look into this today. Clever way to handle multi-page queries. I'll generate a couple hundred projects on my test instance to test it out.

**Comment by ngetchell** [comment]
Also, using invoke-webrequest would allow us to check HTTP status codes as well. That would be for the future though.

**Comment by ngetchell** [comment]
It works. 

works

**Comment by TerrapinStation** [comment]
Cool. Thanks for double checking. Are we ready to push dev to master at
this point?

**Comment by ngetchell** [comment]
I was hoping to get a build process up and running but that is a few days off. Will push to master tonight.

**Comment by TerrapinStation** [comment]
We can wait until build process. I'm fine with that :)

**Pull request merged**
